wezsemoto/urls.py
from django.conf.urls.static import static
from django.urls import path, include

from main.views import index, AdminBikeListView, BikeDetailsView, BikeListView
from wezsemoto import settings

urlpatterns = [
    path('', index, name='index'),
    path('motocykle', BikeListView.as_view(), name='bike_list'),
    path('motocykl/<int:id>', BikeDetailsView.as_view(), name='bike_details'),
    path('motocykl/<int:id>/<str:slug>', BikeDetailsView.as_view(), name='bike_details'),
    path('admin/', include('main.urls.admin'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Max
from django.utils.text import slugify
from django.utils.translation import gettext as _
from ordered_model.models import OrderedModel


class BikeParameters(models.Model):
    name = models.CharField(_('nazwa'), max_length=50)
    capacity = models.CharField(_('pojemność'), max_length=30)
    power = models.CharField(_('moc'), max_length=30)
    torque = models.CharField(_('moment obrotowy'), max_length=30)
    tank_capacity = models.CharField(_('pojemność baku'), max_length=30)
    seat_height = models.CharField(_('wysokość siedzenia'), max_length=30)
    extra = models.CharField(_('dodatkowe wyposażenie'), max_length=255)

    def __str__(self):
        return self.name


class Bike(models.Model):
    name = models.CharField(max_length=100, verbose_name=_('nazwa'))
    brand = models.CharField(max_length=50, verbose_name=_('marka'))
    model = models.CharField(max_length=50, verbose_name=_('model'))
    date_of_production = models.DateField(verbose_name=_('data produkcji'))
    plate_number = models.CharField(max_length=15, verbose_name=_('numer rejestracyjny'))
    is_active = models.BooleanField(_('jest aktywny'), default=True)
    is_visible = models.BooleanField(_('jest widoczny'), default=True)
    slug = models.SlugField()
    short_description = models.TextField(max_length=90, verbose_name=_('krótki opis'), null=True)
    description = models.TextField(max_length=300, verbose_name=_('opis'), null=True)
    bike_parameters = models.ForeignKey(BikeParameters, on_delete=models.SET_NULL, verbose_name=_('parametry'),
                                        null=True)

    def shorten_description(self):
        return self.description[:90] + '...' if len(self.description) > 90 else self.description

    def save(self, *args, **kwargs):
        self.slug = slugify(self.brand) + slugify(self.model)
        super().save(*args, **kwargs)

    def __str__(self):
        # return '%s %s %s' % (self.brand, self.model, self.date_of_production.year)
        return self.name

    class Meta:
        verbose_name = _('motocykl')
        verbose_name_plural = _('motocykle')


class BikePhoto(OrderedModel):
    photo = models.ImageField(verbose_name=_('zdjęcie'), upload_to='bikes')
    bike = models.ForeignKey(Bike, on_delete=models.CASCADE, verbose_name=_('motocykl'))
    order_with_respect_to = 'bike'


class Reservation(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, verbose_name=_('użytkownik'), null=True)
    bike = models.ForeignKey(Bike, on_delete=models.SET_NULL, verbose_name=_('motocykl'), null=True)
    start_date = models.DateField(_('data rozpoczęcia'))
    end_date = models.DateField(_('data zakończenia'))
    information = models.TextField(_('Dodatkowe informacje'))

    class Meta:
        verbose_name = _('rezerwacja')
        verbose_name_plural = _('rezerwacje')


class BikeOffer(models.Model):
    price = models.DecimalField(_('cena'), max_digits=6, decimal_places=0)
    duration = models.CharField(_('okres'), max_length=255)
    bike = models.ForeignKey(Bike, on_delete=models.CASCADE, verbose_name=_('motocykl'))

    def get_price(self):
        return self.price + ' zł'


class Settings(models.Model):
    key = models.CharField(_('klucz'), max_length=30)
    value = models.CharField(_('wartość'), max_length=500)

templates/_layout.html
{% load static %}
{% load compress %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="theme-color" content="#D4A823" />
    <title>Weź se moto - {{ title_appendix }}</title>
    {% compress css %}
        <link rel="stylesheet" type="text/x-scss" href="{% static 'css/brand.scss' %}"/>
        <link rel="stylesheet" type="text/x-scss" href="{% static 'css/main.scss' %}" />
        <link rel="stylesheet" type="text/x-scss" href="{% static 'css/grid.scss' %}"/>
    {% endcompress %}
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body class="{% if active_nav == 'index' %}yellow{% endif %}">
<header>
    <nav class="navbar navbar-expand-lg bg-primary navbar-light shadow">
        <div class="container">
            <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item {% if active_nav == 'index' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'index' %}">Strona główna <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item {% if active_nav == 'motorcycle_list' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'bike_list' %}">Motocykle <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'admin_users' %}">Admin użytkownicy <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'admin_bikes' %}">Admin motocykle <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'admin_bike_parameters' %}">Admin parametry <span class="sr-only">(current)</span></a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<main role="main">

{% block content %}{% endblock %}
</main>
<footer class="footer navbar bg-dark" id="footer">
    <div class="container">
        <span class="text-white-50">Marek Czaplicki @ 2018</span>
    </div>
</footer>
{% compress js %}
    <script type="text/javascript" src="{% static 'lib/jquery/dist/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'lib/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'lib/hammerjs/hammer.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'lib/muuri/dist/muuri.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'lib/@glidejs/glide/dist/glide.min.js' %}"></script>
    {% block script %}{% endblock %}
{% endcompress %}
</body>
</html>

templates/bike_details.html
{% extends '_layout.html' %}
{% load static thumbnail crispy_forms_tags i18n %}
{% block content %}
    <div class="container">
        <div class="glide">
            <div class="glide__track" data-glide-el="track">
                <div class="glide__slides">
                    {% for photo in bike.bikephoto_set.all %}
                        <img class="glide__slide" src="{% get_media_prefix %}{{ photo.photo }}" alt="Zdjęcie">
                    {% endfor %}
                </div>
            </div>
            <div class="glide__arrows" data-glide-el="controls">
                <button class="glide__arrow glide__arrow--left" data-glide-dir="<"><span class="carousel-control-prev-icon" aria-hidden="true" ></span></button>
                <button class="glide__arrow glide__arrow--right" data-glide-dir=">"><span class="carousel-control-next-icon" aria-hidden="true" ></span></button>

            </div>
        </div>
        <div class="row mt-2">
            <div class="col-12">
                <h1>{{ bike.brand }} {{ bike.model }}</h1>
            </div>
            <div class="col-12 col-md-9">
                <div class="col-12 p-0 p-md-3">
                    <h5>{{ bike.description }}</h5>
                </div>
                <div class="col-12 p-0 p-md-3">
                    <h4 class="text-muted" data-toggle="collapse" data-target="#collapse_offers" aria-expanded="true">
                        <i class="material-icons align-middle arrow-down">arrow_drop_down</i>
                        <i class="material-icons align-middle arrow-right">arrow_right</i>
                        {% trans 'Cennik' %}
                    </h4>
                    <div class="collapse show" id="collapse_offers">
                        <ul class="list-inline-horizontal shadow">
                            {% for offer in bike.bikeoffer_set.all %}
                                <li class="list-inline-horizontal-item">
                                    <div class="bg-primary py-4">
                                        <span class="font-weight-bold h2">{{ offer.price }} zł</span>
                                    </div>
                                    <div class="p-1">
                                        <h6 class="my-0 text-muted">{{ offer.duration }}</h6>
                                    </div>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <div class="col-12 p-0 p-md-3">
                    <h4 class="text-muted" data-toggle="collapse" data-target="#collapse_contact" aria-expanded="true">
                        <i class="material-icons align-middle arrow-down">arrow_drop_down</i>
                        <i class="material-icons align-middle arrow-right">arrow_right</i>
                        {% trans 'Skontaktuj się' %}
                    </h4>
                    <div class="card shadow collapse show" id="collapse_contact">
                        <div class="card-body">
                            {% crispy form %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-12 col-md-3">
                <h4 class="text-muted" data-toggle="collapse" data-target="#collapse_parameters" aria-expanded="true">
                    <i class="material-icons align-middle arrow-down">arrow_drop_down</i>
                    <i class="material-icons align-middle arrow-right">arrow_right</i>
                    {% trans 'Parametry' %}
                </h4>
                <div class="collapse show" id="collapse_parameters">
                    <ul class="list-group shadow">
                        <li class="list-group-item">
                            <div>
                                <h6 class="my-0">{% trans "Pojemność" %}</h6>
                            </div>
                            <span class="text-muted">{{ bike.bike_parameters.capacity }}</span>
                        </li>
                        <li class="list-group-item">
                            <div>
                                <h6 class="my-0">{% trans "Moc maksymalna" %}</h6>
                            </div>
                            <span class="text-muted">{{ bike.bike_parameters.power }}</span>
                        </li>
                        <li class="list-group-item">
                            <div>
                                <h6 class="my-0">{% trans "Moment obrotowy" %}</h6>
                            </div>
                            <span class="text-muted">{{ bike.bike_parameters.torque }}</span>
                        </li>
                        <li class="list-group-item">
                            <div>
                                <h6 class="my-0">{% trans "Pojemność baku" %}</h6>
                            </div>
                            <span class="text-muted">{{ bike.bike_parameters.tank_capacity }}</span>
                        </li>
                        <li class="list-group-item">
                            <div>
                                <h6 class="my-0">{% trans "Wysokość siedzenia" %}</h6>
                            </div>
                            <span class="text-muted">{{ bike.bike_parameters.seat_height }}</span>
                        </li>
                        <li class="list-group-item">
                            <div>
                                <h6 class="my-0">{% trans "Dodatkowe wyposażenie" %}</h6>
                            </div>
                            <span class="text-muted">{{ bike.bike_parameters.extra }}</span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block script %}
    <script>
        $(function () {
            let glide = new Glide('.glide', {
                type: 'carousel',
                perView: 1,
                focusAt: 'center',
                peek: {
                    before: 100,
                    after: 100
                },
                breakpoints: {
                    992: {
                        peek: {
                            before: 0,
                            after: 0
                        }
                    },
                    1200: {
                        peek: {
                            before: 50,
                            after: 50
                        }
                    }
                }
            });
            glide.mount();
        })
    </script>
{% endblock %}

templates/bike_list.html
{% extends '_layout.html' %}
{% load static thumbnail %}
{% block content %}
    <div class="container">
        <div class="row justify-content-center">
        {% for bike in object_list %}
            <div class="bike-card">
                <div class="card">
                    {% if bike.bikephoto_set.all %}
                        <div class="carousel slide" data-ride="carousel" id="carousel_{{ bike.id }}">
                            <ol class="carousel-indicators">
                                {% for photo in bike.bikephoto_set.all %}
                                    <li data-target="#carousel_{{ bike.id }}" data-slide-to="{{ forloop.counter0 }}"
                                        class="{% if forloop.counter0 is 0 %}active{% endif %}"></li>
                                {% endfor %}
                            </ol>
                            <div class="carousel-inner">
                            {% for photo in bike.bikephoto_set.all %}
                                <div class="carousel-item {% if forloop.counter0 is 0 %}active{% endif %}">
                                    <img src="{{ photo.photo|thumbnail_url:'bike_card' }}"
                                         alt="Zdjęcie motocykla"
                                         class="card-img-top">
                                </div>
                            {% endfor %}
                            </div>
                            <a class="carousel-control-prev" href="#carousel_{{ bike.id }}" role="button" data-slide="prev">
                                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                            <a class="carousel-control-next" href="#carousel_{{ bike.id }}" role="button" data-slide="next">
                                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                        </div>
                    {% else %}
                        <object class="no-image" data="{% static "img/no_image.svg" %}"></object>
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title">{{ bike.name }}</h5>
                        <p class="card-text">{{ bike.short_description }}</p>
                        <a class="btn btn-primary" href="{% url 'bike_details' bike.id bike.slug %}">Więcej</a>
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
    </div>
{% endblock %}

templates/index.html
{% extends '_layout.html' %}
{% load static %}
{% block content %}
    <div class="center-screen mx-auto">
        <img class="big-logo" src="{% static '/img/logo.svg' %}">
    </div>
{% endblock %}
{% block script %}
    <script>
        $(function () {
            $('footer').addClass('d-none');
        });
    </script>
{% endblock %}